In [37]:
# Importar todo
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline
import seaborn as sns

Importar las bases de datos a dataframes

In [38]:
apodaca = pd.read_csv('csvsFinales/Apodaca.csv') #index_col=0????
escobedo = pd.read_csv('csvsFinales/Escobedo.csv')
garcia = pd.read_csv('csvsFinales/Garcia.csv')
saintPeter = pd.read_csv('csvsFinales/SanPedro.csv')
santaCatarina = pd.read_csv('csvsFinales/SantaCatarina.csv')

In [39]:
apodaca.head()
#escobedo.head()
#garcia.head()
#saintPeter.head()
#santaCatarina.head()

Unnamed: 0   NOX  O3  PM10  RH     SR   TOUT  WSR  WDR NOX_categorias  \
0          19  20.7  28    46   5  0.039  33.81  2.3   11    Intervalo 3   
1          23  60.4   6    74  17  0.000  27.15  1.2  168            NaN   
2          24  90.1   6    89  21  0.000  25.57  2.3  156            NaN   
3          51  21.7  16    40  29  0.000   6.93  3.8  172    Intervalo 3   
4          52  14.1  21    31  30  0.000   7.17  6.2  157    Intervalo 2   

  O3_categorias PM10_categorias RH_categorias SR_categorias TOUT_categorias  \
0   Intervalo 3     Intervalo 5   Intervalo 1   Intervalo 1     Intervalo 4   
1   Intervalo 1             NaN   Intervalo 2   Intervalo 1     Intervalo 3   
2   Intervalo 1             NaN   Intervalo 3   Intervalo 1     Intervalo 3   
3   Intervalo 2     Intervalo 4   Intervalo 3   Intervalo 1     Intervalo 1   
4   Intervalo 3     Intervalo 4   Intervalo 3   Intervalo 1     Intervalo 1   

  WSR_categorias WDR_categorias  
0    Intervalo 1    Intervalo 2  
1    Intervalo 1            NaN  
2    Intervalo 1            NaN  
3    Intervalo 1            NaN  
4    Intervalo 1            NaN

Verificar que sean las mismas columnas antes de concatenar las bases de datos

In [40]:
apodaca.columns == escobedo.columns

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True])

In [41]:
apodaca.columns == garcia.columns

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True])

In [42]:
apodaca.columns == saintPeter.columns

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True])

In [43]:
apodaca.columns == santaCatarina.columns

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True])

Dado que las columnas son todas iguales, se pueden concatenar los datos. Sin embargo, antes de realizar la concatenación se agregarán columnas a cada dataframe especificando el nombre de la planta.

In [44]:
apodaca['Planta'] = 1

In [45]:
escobedo['Planta'] = 2

In [46]:
garcia['Planta'] = 3

In [47]:
saintPeter['Planta'] = 4

In [48]:
santaCatarina['Planta'] = 5

Ahora si, se pueden concatenar las bases de datos

In [49]:
df = pd.concat([apodaca, escobedo, garcia, saintPeter, santaCatarina])
df.head()

Unnamed: 0   NOX  O3  PM10  RH     SR   TOUT  WSR  WDR NOX_categorias  \
0          19  20.7  28  46.0   5  0.039  33.81  2.3   11    Intervalo 3   
1          23  60.4   6  74.0  17  0.000  27.15  1.2  168            NaN   
2          24  90.1   6  89.0  21  0.000  25.57  2.3  156            NaN   
3          51  21.7  16  40.0  29  0.000   6.93  3.8  172    Intervalo 3   
4          52  14.1  21  31.0  30  0.000   7.17  6.2  157    Intervalo 2   

  O3_categorias PM10_categorias RH_categorias SR_categorias TOUT_categorias  \
0   Intervalo 3     Intervalo 5   Intervalo 1   Intervalo 1     Intervalo 4   
1   Intervalo 1             NaN   Intervalo 2   Intervalo 1     Intervalo 3   
2   Intervalo 1             NaN   Intervalo 3   Intervalo 1     Intervalo 3   
3   Intervalo 2     Intervalo 4   Intervalo 3   Intervalo 1     Intervalo 1   
4   Intervalo 3     Intervalo 4   Intervalo 3   Intervalo 1     Intervalo 1   

  WSR_categorias WDR_categorias  Planta  
0    Intervalo 1    Intervalo 2       1  
1    Intervalo 1            NaN       1  
2    Intervalo 1            NaN       1  
3    Intervalo 1            NaN       1  
4    Intervalo 1            NaN       1

In [50]:
df.columns

Index(['Unnamed: 0', 'NOX', 'O3', 'PM10', 'RH', 'SR', 'TOUT', 'WSR', 'WDR',
       'NOX_categorias', 'O3_categorias', 'PM10_categorias', 'RH_categorias',
       'SR_categorias', 'TOUT_categorias', 'WSR_categorias', 'WDR_categorias',
       'Planta'],
      dtype='object')

In [51]:
df = df.drop(['Unnamed: 0','RH_categorias', 'PM10_categorias', 'SR_categorias', 'WSR_categorias', 'TOUT_categorias', 'WDR_categorias', 'NOX_categorias', 'O3_categorias'], axis=1)

In [52]:
df.head()

NOX  O3  PM10  RH     SR   TOUT  WSR  WDR  Planta
0  20.7  28  46.0   5  0.039  33.81  2.3   11       1
1  60.4   6  74.0  17  0.000  27.15  1.2  168       1
2  90.1   6  89.0  21  0.000  25.57  2.3  156       1
3  21.7  16  40.0  29  0.000   6.93  3.8  172       1
4  14.1  21  31.0  30  0.000   7.17  6.2  157       1

In [53]:
df.to_csv('csvsFinales/willyrex.csv')